import { AppSidebar } from "@/components/custom/sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
// import { ThemeToggle } from "@/components/custom/theme-toggle";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProjectLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <SidebarProvider >
                <AppSidebar />
                <SidebarInset >
                    {children}
                </SidebarInset>
            </SidebarProvider>
        </>
    );
}
