import Navbar from "@/components/custom/navbar/navbar";
import type { Metadata } from "next";
// import { ThemeToggle } from "@/components/custom/theme-toggle";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProjectLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
        </>
    );
}
