import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/custom/navbar/navbar";
// import { ThemeToggle } from "@/components/custom/theme-toggle";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
